manual_seed: 1234

kfield_ckpt: "/spaths/checkpoints/kfield/version_1/checkpoints/last.ckpt"

arch_params:
    mdim: 16
    pdim: 8
    edim: 16
    inr_params:
        depth: 8
        hidden: 64
        w0_initial: 2.0
        w0: 1.0
        c: 6.0


task_params:
    lr_inner: 0.01
    inner_steps: 5
    lr: 0.000005
    weight_decay: 0.0
    sched_gamma: 0.99

loader_params:
  batch_size: 150
  num_workers: 8

trainer_params:
  max_epochs: 200

logging_params:
  save_dir: "/spaths/checkpoints"
