shapes:
    rect_x_rng : [0.1, 6.0]
    rect_y_rng : [0.05, 0.15]
    rect_z: 0.1
    sphere_prob: 0.0
    sphere_radius_rng: [0.025, 0.4]

gfield:
    k_inside: 1000
    k_outside: 1000
    qsigma: 3.0

train:
    n_shapes: 2000

test:
   n_shapes: 10

val:
    n_shapes: 10
