manual_seed: 1234

arch_params:
    mod: 12
    q_in: 2
    out: 1
    hidden: 128
    depth: 8
    w0_initial: 7.5
    w0: 1.0
    c: 6.0
    sigmoid: 1

task_params:
    inner_steps: 5
    lr: 0.00025
    weight_decay: 0.0
    sched_gamma: 0.99
    lr_inner: 0.025

loader_params:
  batch_size: 256
  num_workers: 8

trainer_params:
  max_epochs: 200

logging_params:
  save_dir: "/spaths/checkpoints"
