manual_seed: 1234

arch_params:
    mdim: 16
    pdim: 8
    pf_params:
        depth: 8
        hidden: 64
        w0_initial: 10.0
        w0: 1.0
        c: 6.0

    mf_params:
        depth: 5
        hidden: 64
        w0_initial: 1.0
        w0: 1.0
        c: 6.0

task_params:
    lr_inner: 0.01
    inner_steps: 5
    lr: 0.00001
    weight_decay: 0.0
    sched_gamma: 0.999

loader_params:
  batch_size: 100
  num_workers: 8

trainer_params:
  max_epochs: 200

logging_params:
  save_dir: "/spaths/checkpoints"
