manual_seed: 1234

arch_params:
    kdim: 9
    qspline_params:
        depth: 12
        theta_hidden: 128
        w0_initial: 5.0
        w0: 1.0
        c: 6.0
        use_bias: 1

    sigma_params:
        hidden: 64
        depth: 4
        w0_initial: 5.0
        w0: 1.0
        c: 6.0

task_params:
    inner_steps: 5
    lr: 0.00001
    weight_decay: 0.0
    sched_gamma: 0.99
    lr_inner: 0.01

loader_params:
  batch_size: 1000
  num_workers: 8

trainer_params:
  max_epochs: 200

logging_params:
  save_dir: "/spaths/checkpoints"
