train:
    scenes:
        n_scenes: 100000
        sphere_z_max: 6.0
    simulations:
        max_dur: 5.0
    kfield:
        k_per_frame: 5
        nframes: 30

val:
    scenes:
        n_scenes: 10
        sphere_z_max: 6.0
    simulations:
        max_dur: 5.0
    kfield:
        k_per_frame: 5
        nframes: 30

test:
    scenes:
        n_scenes: 100
        sphere_z_max: 6.0
    simulations:
        max_dur: 5.0
    kfield:
        k_per_frame: 5
        nframes: 30
