train:
    scenes:
        n_scenes: 10000
        sphere_z_max: 6.0
    simulations:
        max_dur: 7.0
    kfield:
        segment_dur: 2000.0
        k_per_frame: 5
        noise_scale: 0.05

val:
    scenes:
        n_scenes: 10
        sphere_z_max: 6.0
    simulations:
        max_dur: 7.0
    kfield:
        segment_dur: 2500.0
        k_per_frame: 3
        noise_scale: 0.01
