manual_seed: 1234

arch_params:
    kdim: 16
    qspline_params:
       hidden: 64
       depth: 3
    sigma_params:
        hidden: 64
        depth: 5
        w0_initial: 5.0
        w0: 1.0
        c: 6.0

task_params:
    inner_steps: 4
    lr: 0.00001
    weight_decay: 0.0
    sched_gamma: 0.9
    lr_inner: 0.001

loader_params:
  batch_size: 24
  num_workers: 8

trainer_params:
  max_epochs: 20

logging_params:
  save_dir: "/spaths/checkpoints"
