manual_seed: 1234

arch_params:
    q_in: 4
    out: 1
    hidden: 256
    mod: 16
    depth: 5
    w0_initial: 5.0
    w0: 1.0
    c: 6.0
    sigmoid: 0

task_params:
    inner_steps: 4
    lr: 0.00005
    weight_decay: 0.0
    sched_gamma: 0.9
    lr_inner: 0.01

loader_params:
  batch_size: 12
  num_workers: 4

trainer_params:
  max_epochs: 20

logging_params:
  save_dir: "/spaths/checkpoints"
