manual_seed: 1234

arch_params:
    q_in: 3
    out: 1
    hidden: 256
    mod: 2
    depth: 10

task_params:
    inner_steps: 3
    lr: 0.00001
    weight_decay: 0.0
    sched_gamma: 1.0
    lr_inner: 0.01

data_params:
  train_path: "/spaths/datasets/spherical_geo_train.beton"
  test_path: "/spaths/datasets/spherical_geo_test.beton"

loader_params:
  batch_size: 64
  num_workers: 8

trainer_params:
  max_epochs: 1000

logging_params:
  save_dir: "/spaths/checkpoints"
